package com.example.util

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "library" to "Library",
            "history" to "History",
            "settings" to "Settings",
            "search_placeholder" to "Search books & comics...",
            "activity_summary" to "Reading Activity Summary",
            "total_books" to "Total Books",
            "time_read" to "Time Read",
            "favorites" to "Favorites",
            "finished" to "Finished",
            "reader_config" to "Reader Configuration",
            "reading_layout" to "Reading Layout",
            "reader_brightness" to "Reader Brightness",
            "keep_screen_on" to "Keep Screen On",
            "screen_rotation" to "Screen Rotation",
            "app_theme" to "App Theme",
            "appearance_themes" to "Appearance & Themes",
            "light" to "Light",
            "dark" to "Dark",
            "amoled" to "AMOLED Black",
            "material_you" to "Material You",
            "accent_color" to "Accent Color",
            "corner_style" to "Corner Style",
            "ui_font_size" to "UI Font Size",
            "icons_style" to "Icons Style",
            "layout_spacing" to "Layout Spacing",
            "navigation_style" to "Navigation Style",
            "language" to "App Language",
            "volume_keys" to "Volume Keys Page Turn",
            "manage_folders" to "Manage Folders",
            "folder_switcher" to "Folder Switcher",
            "add_folder" to "Add Folder",
            "remove_folder" to "Remove",
            "rename_alias" to "Rename Alias",
            "refresh" to "Refresh",
            "backup_restore" to "Backup & Restore Settings",
            "reset_appearance" to "Reset Appearance",
            "restore_defaults" to "Restore Defaults",
            "auto_scroll" to "Auto Scroll",
            "scroll_speed" to "Scroll Speed",
            "saved_pages" to "Saved Pages",
            "bookmarks" to "Bookmarks",
            "save_current_page" to "Save Current Page",
            "saved_pages_list" to "Manually Saved Pages",
            "auto_rotation" to "Auto Rotation",
            "portrait" to "Portrait",
            "landscape" to "Landscape"
        ),
        "es" to mapOf(
            "library" to "Biblioteca",
            "history" to "Historial",
            "settings" to "Ajustes",
            "search_placeholder" to "Buscar libros y cómics...",
            "activity_summary" to "Resumen de Lectura",
            "total_books" to "Libros Totales",
            "time_read" to "Tiempo Leído",
            "favorites" to "Favoritos",
            "finished" to "Terminados",
            "reader_config" to "Configuración del Lector",
            "reading_layout" to "Diseño de Lectura",
            "reader_brightness" to "Brillo del Lector",
            "keep_screen_on" to "Mantener Pantalla Encendida",
            "screen_rotation" to "Rotación de Pantalla",
            "app_theme" to "Tema de la Aplicación",
            "appearance_themes" to "Aspecto y Temas",
            "light" to "Claro",
            "dark" to "Oscuro",
            "amoled" to "Negro AMOLED",
            "material_you" to "Material You",
            "accent_color" to "Color de Acento",
            "corner_style" to "Estilo de Esquinas",
            "ui_font_size" to "Tamaño de Fuente",
            "icons_style" to "Estilo de Iconos",
            "layout_spacing" to "Espaciado de Diseño",
            "navigation_style" to "Estilo de Navegación",
            "language" to "Idioma de la Aplicación",
            "volume_keys" to "Pasar Páginas con Volumen",
            "manage_folders" to "Administrar Carpetas",
            "folder_switcher" to "Selector de Carpetas",
            "add_folder" to "Añadir Carpeta",
            "remove_folder" to "Eliminar",
            "rename_alias" to "Renombrar Alias",
            "refresh" to "Actualizar",
            "backup_restore" to "Copia de Seguridad",
            "reset_appearance" to "Restablecer Aspecto",
            "restore_defaults" to "Restaurar Predeterminados",
            "auto_scroll" to "Desplazamiento Automático",
            "scroll_speed" to "Velocidad de Desplazamiento",
            "saved_pages" to "Páginas Guardadas",
            "bookmarks" to "Marcadores",
            "save_current_page" to "Guardar Página Actual",
            "saved_pages_list" to "Páginas Guardadas Manualmente",
            "auto_rotation" to "Rotación Auto",
            "portrait" to "Retrato",
            "landscape" to "Horizontal"
        ),
        "fr" to mapOf(
            "library" to "Bibliothèque",
            "history" to "Historique",
            "settings" to "Paramètres",
            "search_placeholder" to "Rechercher des livres...",
            "activity_summary" to "Résumé de Lecture",
            "total_books" to "Total de Livres",
            "time_read" to "Temps de Lecture",
            "favorites" to "Favoris",
            "finished" to "Terminé",
            "reader_config" to "Configuration de Lecture",
            "reading_layout" to "Mise en Page",
            "reader_brightness" to "Luminosité",
            "keep_screen_on" to "Garder l'Écran Allumé",
            "screen_rotation" to "Rotation de l'Écran",
            "app_theme" to "Thème de l'App",
            "appearance_themes" to "Apparence & Thèmes",
            "light" to "Clair",
            "dark" to "Sombre",
            "amoled" to "Noir AMOLED",
            "material_you" to "Material You",
            "accent_color" to "Couleur d'Accent",
            "corner_style" to "Style de Coins",
            "ui_font_size" to "Taille de Police",
            "icons_style" to "Style d'Icônes",
            "layout_spacing" to "Espacement de l'App",
            "navigation_style" to "Style de Navigation",
            "language" to "Langue de l'Application",
            "volume_keys" to "Tourner avec Volume",
            "manage_folders" to "Gérer les Dossiers",
            "folder_switcher" to "Sélecteur de Dossiers",
            "add_folder" to "Ajouter Dossier",
            "remove_folder" to "Supprimer",
            "rename_alias" to "Renommer l'Alias",
            "refresh" to "Actualiser",
            "backup_restore" to "Sauvegarde & Restauration",
            "reset_appearance" to "Réinitialiser l'Aspect",
            "restore_defaults" to "Valeurs par Défaut",
            "auto_scroll" to "Défilement Automatique",
            "scroll_speed" to "Vitesse de Défilement",
            "saved_pages" to "Pages Enregistrées",
            "bookmarks" to "Signets",
            "save_current_page" to "Enregistrer Page Actuelle",
            "saved_pages_list" to "Pages Enregistrées Manuellement",
            "auto_rotation" to "Rotation Auto",
            "portrait" to "Portrait",
            "landscape" to "Paysage"
        ),
        "ja" to mapOf(
            "library" to "本棚",
            "history" to "読書履歴",
            "settings" to "設定",
            "search_placeholder" to "書籍・コミックを検索...",
            "activity_summary" to "読書活動概要",
            "total_books" to "総書籍数",
            "time_read" to "読書時間",
            "favorites" to "お気に入り",
            "finished" to "読了",
            "reader_config" to "リーダー設定",
            "reading_layout" to "読書レイアウト",
            "reader_brightness" to "画面輝度",
            "keep_screen_on" to "画面常時点灯",
            "screen_rotation" to "画面の回転",
            "app_theme" to "アプリのテーマ",
            "appearance_themes" to "外観とテーマ",
            "light" to "ライト",
            "dark" to "ダーク",
            "amoled" to "AMOLED ブラック",
            "material_you" to "Material You 動的カラー",
            "accent_color" to "アクセントカラー",
            "corner_style" to "角の丸み",
            "ui_font_size" to "文字サイズ",
            "icons_style" to "アイコンスタイル",
            "layout_spacing" to "レイアウト余白",
            "navigation_style" to "ナビゲーションスタイル",
            "language" to "表示言語",
            "volume_keys" to "音量キーでページをめくる",
            "manage_folders" to "フォルダ管理",
            "folder_switcher" to "フォルダ切り替え",
            "add_folder" to "フォルダを追加",
            "remove_folder" to "削除",
            "rename_alias" to "別名を変更",
            "refresh" to "更新",
            "backup_restore" to "設定バックアップ",
            "reset_appearance" to "外観をリセット",
            "restore_defaults" to "既定値に戻す",
            "auto_scroll" to "自動スクロール",
            "scroll_speed" to "スクロール速度",
            "saved_pages" to "保存されたページ",
            "bookmarks" to "しおり",
            "save_current_page" to "現在のページを保存",
            "saved_pages_list" to "手動で保存したページ",
            "auto_rotation" to "自動回転",
            "portrait" to "縦画面",
            "landscape" to "横画面"
        ),
        "zh" to mapOf(
            "library" to "书架",
            "history" to "阅读历史",
            "settings" to "设置",
            "search_placeholder" to "搜索书籍与漫画...",
            "activity_summary" to "阅读活动概要",
            "total_books" to "总书籍",
            "time_read" to "阅读时间",
            "favorites" to "收藏",
            "finished" to "已读完",
            "reader_config" to "阅读器配置",
            "reading_layout" to "阅读布局",
            "reader_brightness" to "阅读亮度",
            "keep_screen_on" to "保持屏幕常亮",
            "screen_rotation" to "屏幕旋转",
            "app_theme" to "应用主题",
            "appearance_themes" to "外观与主题",
            "light" to "浅色",
            "dark" to "深色",
            "amoled" to "AMOLED 纯黑",
            "material_you" to "Material You 动态色彩",
            "accent_color" to "强调色",
            "corner_style" to "圆角风格",
            "ui_font_size" to "字体大小",
            "icons_style" to "图标风格",
            "layout_spacing" to "布局密度",
            "navigation_style" to "导航栏样式",
            "language" to "应用语言",
            "volume_keys" to "音量键翻页",
            "manage_folders" to "管理文件夹",
            "folder_switcher" to "文件夹切换器",
            "add_folder" to "添加文件夹",
            "remove_folder" to "移除",
            "rename_alias" to "重命名别名",
            "refresh" to "刷新",
            "backup_restore" to "配置备份与恢复",
            "reset_appearance" to "重置外观",
            "restore_defaults" to "恢复默认设置",
            "auto_scroll" to "自动滚动",
            "scroll_speed" to "滚动速度",
            "saved_pages" to "已存页面",
            "bookmarks" to "书签",
            "save_current_page" to "保存当前页面",
            "saved_pages_list" to "手动保存的页面",
            "auto_rotation" to "自动旋转",
            "portrait" to "竖屏",
            "landscape" to "横屏"
        )
    )

    fun getString(lang: String, key: String): String {
        val dict = translations[lang] ?: translations["en"]!!
        return dict[key] ?: translations["en"]?.get(key) ?: key
    }
}
